title: Ecossistema de Software Elixir
description: Alguns dos atores do ecossistema da linguagem Elixir.
theme: minima

# Como é um Project Page, o baseurl deve ser o nome do repositório
url: "https://elixiremfoco.github.io"
baseurl: "/ecossistema"

# Opções extras
lang: pt-BR
author: Lucas Leyser
github_username: Lucas_Leyser
